### PR TITLE
Postgres migration

### LINKED ISSUE #203: mysqld.exe is still running after stopping bootRunDev
**Describe the bug**
mysqld.exe is still running after stopping bootRunDev via stop button or CTRL+F2 from intellij

**To Reproduce**
1. Go to 'gradle'
2. Click on 'bootRunDev'
3. Click on 'stop'
4. Click on 'bootRunDev'
5. You will see the error because mysqld.exe is not closing properly

**Expected behavior**
To close it with the stop, it is preventing me from restarting dev env more easily.

**Logs**
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.flywaydb.core.Flyway]: Factory method 'flyway' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dataSource' defined in class path resource [pl/starchasers/up/configuration/EmbeddedMariadbConfiguration.class]: Unsatisfied dependency expressed through method 'dataSource' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mariaDB4jSpringService': Invocation of init method failed; nested exception is java.lang.IllegalStateException: MariaDB4jSpringService start() failed
org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.flywaydb.core.Flyway]: Factory method 'flyway' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dataSource' defined in class path resource [pl/starchasers/up/configuration/EmbeddedMariadbConfiguration.class]: Unsatisfied dependency expressed through method 'dataSource' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mariaDB4jSpringService': Invocation of init method failed; nested exception is java.lang.IllegalStateException: MariaDB4jSpringService start() failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dataSource' defined in class path resource [pl/starchasers/up/configuration/EmbeddedMariadbConfiguration.class]: Unsatisfied dependency expressed through method 'dataSource' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mariaDB4jSpringService': Invocation of init method failed; nested exception is java.lang.IllegalStateException: MariaDB4jSpringService start() failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mariaDB4jSpringService': Invocation of init method failed; nested exception is java.lang.IllegalStateException: MariaDB4jSpringService start() failed
java.lang.IllegalStateException: MariaDB4jSpringService start() failed
ch.vorburger.exec.ManagedProcessException: An error occurred while starting the database
ch.vorburger.exec.ManagedProcessException: Asked to wait for "mysqld.exe: ready for connections." from Program [C:\Users\KUBOCZ~1\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=C:\Users\Kuboczoch\AppData\Local\Temp\MariaDB4j\base, --datadir=D:\WebstormProjects\up\spring-app\database, --port=3308] (in working directory C:\Users\KUBOCZ~1\AppData\Local\Temp\MariaDB4j\base), but it already exited! (without that message in console), last 100 lines of console:
Process 'command 'C:\Program Files\Java\jdk-11.0.8\bin\java.exe'' finished with non-zero exit value 1
```

**Desktop (please complete the following information):**
 - OS: Windows

### LINKED ISSUE #212: Migrate to postgres

### LINKED ISSUE #223: migrate to kotlin-exposed

### PR DESCRIPTION
**Pull request by KocproZ**
Replaced mariadb with postgres, removed Users, replaced Hibernate with ktorm

### CODE REVIEW

File: spring-app/src/main/kotlin/pl/starchasers/up/configuration/MvcConfiguration.kt [hunk 1]
```diff
@@ -20,9 +20,9 @@ class MvcConfiguration : WebMvcConfigurer {
             .addResourceLocations("classpath:static/manifest.webmanifest")
             .setCacheControl(CacheControl.maxAge(7, TimeUnit.DAYS))
 
-        registry.addResourceHandler("/**")
-            .addResourceLocations("classpath:static/")
-            .setCacheControl(CacheControl.maxAge(365, TimeUnit.DAYS))
+//        registry.addResourceHandler("/**")
```
Comment (HubertBalcerzak) [inline spring-app/src/main/kotlin/pl/starchasers/up/configuration/MvcConfiguration.kt]: is this replaced by something else?

File: spring-app/src/main/kotlin/pl/starchasers/up/controller/UploadController.kt [hunk 2]
```diff
@@ -41,19 +37,16 @@ class UploadController(
...
-        val contentType = ContentType(
+    fun anonymousUpload(@RequestParam file: MultipartFile): UploadCompleteResponseDTO {
+        val contentType =
             if (file.contentType == null || file.contentType!!.isBlank()) "application/octet-stream"
             else file.contentType!!
-        )
 
         return fileService.createFile(
             BufferedInputStream(file.inputStream),
-            Filename(file.originalFilename ?: "file"),
```
Comment (HubertBalcerzak) [inline spring-app/src/main/kotlin/pl/starchasers/up/controller/UploadController.kt:53]: i think you restored `Filename` and `Filesize` classes, but they are still removed here

File: spring-app/src/main/kotlin/pl/starchasers/up/repository/FileEntryRepository.kt [hunk 3]
```diff
@@ -1,30 +1,80 @@
...
+                    accessToken = it[table.accessToken]?.let(::FileAccessToken),
+                    contentType = MimeType.valueOf(it[table.contentType]!!),
+                    createdAt = it[table.createdAt]!!,
+                    encrypted = it[table.encrypted]!!,
+                    filename = FileName(it[table.filename]!!),
+                    key = FileKey(it[table.key]!!),
+                    password = it[table.password]?.let(::FilePassword),
+                    size = FileSize(it[table.size]!!),
+                    toDeleteAt = it[table.deleteAt]
+                )
```
Comment (HubertBalcerzak) [inline spring-app/src/main/kotlin/pl/starchasers/up/repository/FileEntryRepository.kt]: can be extracted to a method

File: spring-app/src/main/kotlin/pl/starchasers/up/service/FileService.kt [hunk 4]
```diff
@@ -54,81 +50,65 @@ class FileServiceImpl(
...
+            set(it.deleteAt, toDeleteAt)
+        }
+
+        return UploadCompleteResponseDTO(key, accessToken, toDeleteAt)
     }
 
-    override fun verifyFileAccess(fileEntry: FileEntry, accessToken: FileAccessToken?, user: User?): Boolean {
-        return (user != null && fileEntry.owner == user) || fileEntry.accessToken == accessToken
+    override fun verifyFileAccess(fileEntry: FileEntry, accessToken: FileAccessToken?): Boolean {
+        return (fileEntry.accessToken != null) && fileEntry.accessToken == accessToken
```
Comment (HubertBalcerzak) [inline spring-app/src/main/kotlin/pl/starchasers/up/service/FileService.kt:84]: why is accessToken optional?

File: spring-app/src/main/kotlin/pl/starchasers/up/service/FileService.kt [hunk 5]
```diff
@@ -54,81 +50,65 @@ class FileServiceImpl(
...
+            set(it.accessToken, accessToken)
+            set(it.contentType, actualContentType)
+            set(it.createdAt, Instant.now())
+            set(it.encrypted, false)
+            set(it.filename, filename)
+            set(it.key, key.value)
+            set(it.password, null)
+            set(it.size, size)
+            set(it.deleteAt, toDeleteAt)
+        }
```
Comment (HubertBalcerzak) [inline spring-app/src/main/kotlin/pl/starchasers/up/service/FileService.kt]: feels a bit weird to have this mapping in a service. Is there any type safety mechanism if one field was forgotten?

File: spring-app/src/main/kotlin/pl/starchasers/up/service/FileService.kt [hunk 6]
```diff
@@ -54,81 +50,65 @@ class FileServiceImpl(
...
+    override fun verifyFileAccess(fileEntry: FileEntry, accessToken: FileAccessToken?): Boolean {
+        return (fileEntry.accessToken != null) && fileEntry.accessToken == accessToken
     }
 
-    override fun verifyFileAccess(fileKey: FileKey, accessToken: FileAccessToken?, user: User?): Boolean =
+    override fun verifyFileAccess(fileKey: FileKey, accessToken: FileAccessToken?): Boolean =
         fileEntryRepository
             .findExistingFileByKey(fileKey)
-            ?.let { verifyFileAccess(it, accessToken, user) } ?: false
+            ?.let { verifyFileAccess(it, accessToken) } == true
```
Comment (HubertBalcerzak) [inline spring-app/src/main/kotlin/pl/starchasers/up/service/FileService.kt]: `== true` not needed

File: spring-app/src/main/kotlin/pl/starchasers/up/service/FileService.kt (hunk 4 above)
Comment (KocproZ) [reply spring-app/src/main/kotlin/pl/starchasers/up/service/FileService.kt:84]: Right, It's has no business being optional here.

File: spring-app/src/main/kotlin/pl/starchasers/up/service/FileService.kt (hunk 6 above)
Comment (KocproZ) [reply spring-app/src/main/kotlin/pl/starchasers/up/service/FileService.kt]: Right, on null it shuld return 404

File: spring-app/src/main/kotlin/pl/starchasers/up/configuration/MvcConfiguration.kt (hunk 1 above)
Comment (KocproZ) [reply spring-app/src/main/kotlin/pl/starchasers/up/configuration/MvcConfiguration.kt]: I was testing something and forgot to uncomment this

File: spring-app/src/main/kotlin/pl/starchasers/up/controller/UploadController.kt (hunk 2 above)
Comment (KocproZ) [reply spring-app/src/main/kotlin/pl/starchasers/up/controller/UploadController.kt:53]: Indeed

File: spring-app/src/main/kotlin/pl/starchasers/up/service/FileService.kt (hunk 5 above)
Comment (KocproZ) [reply spring-app/src/main/kotlin/pl/starchasers/up/service/FileService.kt]: Not with this api. It would be possible with entities, but we wanted to avoid that.

**Review by HubertBalcerzak — APPROVED** [review]
